export const CURRENCIES_DATA_IS_SET = 'CURRENCIES_DATA_IS_SET',
	SECOND_CURRENCY_IS_SET = 'SECOND_CURRENCY_IS_SET',
	LOADING_STATUS_IS_SET = 'LOADING_STATUS_IS_SET',
	TOGGLE_FAVORITE_STATUS = 'TOGGLE_FAVORITE_STATUS',
	STATIC_DATA_STATUS = 'STATIC_DATA_STATUS',
	ERROR = 'ERROR';
